spring:
  datasource:
    name: power_admin
    url: jdbc:mysql://192.168.50.62:3306/power_admin?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 1
      max-wait: 30000
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-log-level: WARN
          slow-sql-millis: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: "*.js,*.css,/druid/*"