spring:
  application:
    name: SpringBootLearn

  profiles:
    active: dev # 默认加载的Profile，可以在启动是通过修改spring.profiles.active属性来变更

logging:
  file:
    path: logs
    name: ''  # 清空文件名，不生成日志文件
  level:
    #    root: DEBUG
    root: INFO # 控制台仍输出INFO及以上级别日志
    org.springframework.jdbc: DEBUG
    com.alibaba.druid: DEBUG

server: # Spring Boot内置的配置项，用于配置Web服务器相关参数
  port: 8088 # 服务端口号
  #  The accepted certificate will be saved in truststore /Users/aecg/Library/Application Support/JetBrains/IntelliJIdea2023.3/ssl/cacerts with the default password changeitv
#  port: 8443 # 服务端口号
#  ssl:
#    # 服务证书
#    key-store: classpath:cert/server.p12
#    key-store-password: 123456
#    key-password: 123456
#    key-store-type: PKCS12
#    key-alias: 1
#    # CA证书
#    trust-store: classpath:cert/ca.p12
#    trust-store-password: 123456
#    trust-store-type: PKCS12
#  http2:
#    enabled: true
  servlet:
    encoding: # 编码强制都使用UTF-8
      force: true # 强制覆盖charset
      charset: UTF-8



minio:
  endpoint: http://192.168.2.99:9000 #MinIO服务所在地址
  bucketName: zyp-bucket  #存储桶名称
  accessKey: XorhHtWNw3kxBVAC12Hv #访问的key
  secretKey: 115mQ7SaaejbAh6uTnnQZF9ZmHENFwXbrC35UfhI #访问的秘钥
#  accessKey: minioadmin #访问的key
#  secretKey: minioadmin #访问的秘钥



welcome: # 自定义的配置
  content: 'Welcome to the basic non env'


my:
  service:
    enabled: true
    remote-address: 192.168.1.1
    security:
      username: "admin"
      password: "123456"
      roles:
        - "USER"
        - "ADMIN"

