### 登录
#@force_http2
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

> {%
    client.test("Request executed successfully", function() {
      client.assert(response.status === 200, "Response status is not 200")
    });
    client.global.set("token", response.body.data.token)
    client.log("response.body.data.token: " + response.body.data.token)
%}

### 当前用户
GET {{baseUrl}}/current_user
Accept: application/json
Authorization: {{ token }}
X-Access-Token: {{ token }}


### 权限列表
GET {{baseUrl}}/permissions?page=1&size=1
Accept: application/json
Authorization: {{ token }}
X-Access-Token: {{ token }}


### 上传一个文件，并附带一些表单字段
POST {{baseUrl}}/oss/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{ token }}
X-Access-Token: {{ token }}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="HELP.md"
Content-Type: text/plain

< /Users/aecg/IdeaProjects/SpringBootLearn/HELP.md

--WebAppBoundary
Content-Disposition: form-data; name="description"
Content-Type: text/plain

这是一个文件描述

--WebAppBoundary--


###
WEBSOCKET wss://127.0.0.1:8443/ws
